name: push

on:
  push:
    branches:
      - '**'
env:
  IMAGE_NAME: maximus335/devops-for-programmers-project-74:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Import environment variables from a file
        uses: cardinalby/export-env-action@v1
        with:
          envFile: '.env.example'
          expand: 'true'
      - name: run tests
        run: make compose-test

      - name: docker buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline
          push: true
          tags: ${{ env.IMAGE_NAME }}
